/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car2.glb 
Author: Ricy (https://sketchfab.com/ngon_3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-w1-b4183ce6d52a4a8796b82481f2fc8119
Title: Mclaren W1
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/car2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, -Math.PI]}>
          <group name="cf0650bb25254001830c0bfcd2afaceefbx" rotation={[-Math.PI, 0, 0]} scale={0.025}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="wing" position={[72.049, 867.839, 297.536]}>
                  <mesh name="wing_Acrylic_Opaque_Black_0" geometry={nodes.wing_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                </group>
                <group name="L_Door" position={[44.223, 17.858, 415.686]} rotation={[0, 1.567, 1.571]}>
                  <group name="Object_47" position={[588.453, -292.986, -44.223]}>
                    <mesh name="L_Door_Carpaint_Flakes_Ruby_0" geometry={nodes.L_Door_Carpaint_Flakes_Ruby_0.geometry} material={materials.Carpaint_Flakes_Ruby} />
                    <mesh name="L_Door_black_0" geometry={nodes.L_Door_black_0.geometry} material={materials.black} />
                    <mesh name="L_Door_Acrylic_Opaque_Black_0" geometry={nodes.L_Door_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                    <mesh name="L_Door_Glass_Smoked_0" geometry={nodes.L_Door_Glass_Smoked_0.geometry} material={materials.Glass_Smoked} />
                    <mesh name="L_Door_Material_#1244_0" geometry={nodes['L_Door_Material_#1244_0'].geometry} material={materials.Material_1244} />
                    <mesh name="L_Door_Material_#1637_0" geometry={nodes['L_Door_Material_#1637_0'].geometry} material={materials.Material_1637} />
                    <mesh name="L_Door_Glass_Mirror_0" geometry={nodes.L_Door_Glass_Mirror_0.geometry} material={materials.Glass_Mirror} />
                    <mesh name="L_Door_Material_#1559_0" geometry={nodes['L_Door_Material_#1559_0'].geometry} material={materials.Material_1559} />
                  </group>
                </group>
                <group name="R_Door" position={[-28.97, 17.858, 415.686]} rotation={[Math.PI / 2, 1.571, 0]}>
                  <group name="Object_111" position={[588.453, -292.986, -44.223]}>
                    <mesh name="R_Door_Carpaint_Flakes_Ruby_0" geometry={nodes.R_Door_Carpaint_Flakes_Ruby_0.geometry} material={materials.Carpaint_Flakes_Ruby} />
                    <mesh name="R_Door_black_0" geometry={nodes.R_Door_black_0.geometry} material={materials.black} />
                    <mesh name="R_Door_Acrylic_Opaque_Black_0" geometry={nodes.R_Door_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                    <mesh name="R_Door_Glass_Smoked_0" geometry={nodes.R_Door_Glass_Smoked_0.geometry} material={materials.Glass_Smoked} />
                    <mesh name="R_Door_Material_#1244_0" geometry={nodes['R_Door_Material_#1244_0'].geometry} material={materials.Material_1244} />
                    <mesh name="R_Door_Glass_Mirror_0" geometry={nodes.R_Door_Glass_Mirror_0.geometry} material={materials.Glass_Mirror} />
                    <mesh name="R_Door_Material_#1663_0" geometry={nodes['R_Door_Material_#1663_0'].geometry} material={materials.Material_1663} />
                    <mesh name="R_Door_Material_#1675_0" geometry={nodes['R_Door_Material_#1675_0'].geometry} material={materials.Material_1675} />
                    <mesh name="R_Door_Material_#1625_0" geometry={nodes['R_Door_Material_#1625_0'].geometry} material={materials.Material_1625} />
                  </group>
                </group>
                <group name="w1_body" position={[7.482, 7.382, 199.95]} rotation={[Math.PI / 2, 1.571, 0]}>
                  <group name="Object_5" position={[598.929, -77.25, -7.482]}>
                    <mesh name="w1_body_Carpaint_Flakes_Ruby_0" geometry={nodes.w1_body_Carpaint_Flakes_Ruby_0.geometry} material={materials.Carpaint_Flakes_Ruby} />
                    <mesh name="w1_body_black_0" geometry={nodes.w1_body_black_0.geometry} material={materials.black} />
                    <mesh name="w1_body_Acrylic_Opaque_Black_0" geometry={nodes.w1_body_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                  </group>
                </group>
                <group name="w1_top" position={[3.311, 55.29, 273.536]}>
                  <mesh name="w1_top_Acrylic_Opaque_Black_0" geometry={nodes.w1_top_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                  <mesh name="w1_top_Material_#1244_0" geometry={nodes['w1_top_Material_#1244_0'].geometry} material={materials.Material_1244} />
                  <mesh name="w1_top_black_0" geometry={nodes.w1_top_black_0.geometry} material={materials.black} />
                  <mesh name="w1_top_Material_#699_0" geometry={nodes['w1_top_Material_#699_0'].geometry} material={materials.Material_699} />
                  <mesh name="w1_top_Material_#770_0" geometry={nodes['w1_top_Material_#770_0'].geometry} material={materials.Material_770} />
                  <mesh name="w1_top_Material_#1065_0" geometry={nodes['w1_top_Material_#1065_0'].geometry} material={materials.Material_1065} />
                  <mesh name="w1_top_Material_#1041_0" geometry={nodes['w1_top_Material_#1041_0'].geometry} material={materials.Material_1041} />
                  <mesh name="w1_top_silver_0" geometry={nodes.w1_top_silver_0.geometry} material={materials.silver} />
                </group>
                <group name="side" position={[0, -215.993, 65.549]} rotation={[Math.PI / 2, 1.571, 0]}>
                  <mesh name="side_Acrylic_Opaque_Black_0" geometry={nodes.side_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                  <mesh name="side_black_0" geometry={nodes.side_black_0.geometry} material={materials.black} />
                </group>
                <group name="headlights" position={[7.482, -692.436, 203.059]} rotation={[Math.PI / 2, 1.571, 0]}>
                  <group name="Object_22" position={[1298.747, -80.359, -7.482]}>
                    <mesh name="headlights_Material_#425_0" geometry={nodes['headlights_Material_#425_0'].geometry} material={materials.Material_425} />
                    <mesh name="headlights_Material_#631_0" geometry={nodes['headlights_Material_#631_0'].geometry} material={materials.Material_631} />
                    <mesh name="headlights_Acrylic_Opaque_Black_0" geometry={nodes.headlights_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                  </group>
                </group>
                <group name="f_bumper" position={[7.482, -705.855, 90.026]} rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_27" position={[191.756, -9.653, -705.855]}>
                    <mesh name="f_bumper_Acrylic_Opaque_Black_0" geometry={nodes.f_bumper_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                    <mesh name="f_bumper_black_0" geometry={nodes.f_bumper_black_0.geometry} material={materials.black} />
                  </group>
                </group>
                <group name="tailights" position={[7.482, 773.391, 270.098]} rotation={[Math.PI / 2, 1.571, 0]}>
                  <group name="Object_31" position={[-168.43, -147.398, -7.482]}>
                    <mesh name="tailights_Material_#1015_0" geometry={nodes['tailights_Material_#1015_0'].geometry} material={materials.Material_1015} />
                  </group>
                </group>
                <group name="glass" position={[3.311, 55.29, 273.536]}>
                  <mesh name="glass_Glass_Smoked_0" geometry={nodes.glass_Glass_Smoked_0.geometry} material={materials.Glass_Smoked} />
                </group>
                <group name="underside" position={[0, 606.311, 122.7]} rotation={[Math.PI / 2, 1.571, 0]}>
                  <mesh name="underside_black_0" geometry={nodes.underside_black_0.geometry} material={materials.black} />
                  <mesh name="underside_Material_#1100_0" geometry={nodes['underside_Material_#1100_0'].geometry} material={materials.Material_1100} />
                </group>
                <group name="r_Diffuser" position={[7.481, 806.483, 124.22]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1, 1.25, 1]}>
                  <group name="Object_41" position={[-79.79, 18.999, 54.463]}>
                    <mesh name="r_Diffuser_Acrylic_Opaque_Black_0" geometry={nodes.r_Diffuser_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                    <mesh name="r_Diffuser_Material_#1016_0" geometry={nodes['r_Diffuser_Material_#1016_0'].geometry} material={materials.Material_1016} />
                    <mesh name="r_Diffuser_Material_#1028_0" geometry={nodes['r_Diffuser_Material_#1028_0'].geometry} material={materials.Material_1028} />
                    <mesh name="r_Diffuser_Material_#937_0" geometry={nodes['r_Diffuser_Material_#937_0'].geometry} material={materials.Material_937} />
                  </group>
                </group>
                <group name="interior" position={[3.311, 55.29, 273.536]}>
                  <mesh name="interior_Acrylic_Opaque_Black_0" geometry={nodes.interior_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                  <mesh name="interior_Material_#1783_0" geometry={nodes['interior_Material_#1783_0'].geometry} material={materials.Material_1783} />
                  <mesh name="interior_silver_0" geometry={nodes.interior_silver_0.geometry} material={materials.silver} />
                  <mesh name="interior_Material_#1350_0" geometry={nodes['interior_Material_#1350_0'].geometry} material={materials.Material_1350} />
                  <mesh name="interior_Material_#1337_0" geometry={nodes['interior_Material_#1337_0'].geometry} material={materials.Material_1337} />
                  <mesh name="interior_black_0" geometry={nodes.interior_black_0.geometry} material={materials.black} />
                  <mesh name="interior_Material_#1770_0" geometry={nodes['interior_Material_#1770_0'].geometry} material={materials.Material_1770} />
                </group>
                <group name="tire" position={[320.371, -444.104, 119.02]} rotation={[Math.PI / 2, 1.57, 0]} scale={[1, 1, 2.278]}>
                  <group name="Object_65" position={[0, 0, -29.917]}>
                    <mesh name="tire_Material_#1003_0" geometry={nodes['tire_Material_#1003_0'].geometry} material={materials.Material_1003} />
                    <mesh name="tire_Material_#1192_0" geometry={nodes['tire_Material_#1192_0'].geometry} material={materials.Material_1192} />
                  </group>
                  <group name="rim" position={[0, 0, -0.575]}>
                    <group name="Object_69" position={[0, 0, -29.343]}>
                      <mesh name="rim_Material_#1180_0" geometry={nodes['rim_Material_#1180_0'].geometry} material={materials.Material_1180} />
                      <mesh name="rim_Acrylic_Opaque_Black_0" geometry={nodes.rim_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                    </group>
                  </group>
                  <group name="brake" position={[59.332, -11.246, 12.759]} scale={[1, 1, 0.516]}>
                    <group name="Object_73" position={[5.429, 7.302, 4.795]}>
                      <mesh name="brake_Material_#1207_0" geometry={nodes['brake_Material_#1207_0'].geometry} material={materials.Material_1207} />
                    </group>
                    <group name="brake_disc" position={[-59.485, 11.611, -12.471]} scale={[1, 1, 0.851]}>
                      <group name="Object_76" position={[0, 0, 16.985]}>
                        <mesh name="brake_disc_Material_#1208_0" geometry={nodes['brake_disc_Material_#1208_0'].geometry} material={materials.Material_1208} />
                        <mesh name="brake_disc_Acrylic_Opaque_Black_0" geometry={nodes.brake_disc_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="tire001" position={[320.371, 598.48, 119.02]} rotation={[Math.PI / 2, 1.57, 0]} scale={[1, 1, 2.278]}>
                  <group name="Object_80" position={[0, 0, -29.917]}>
                    <mesh name="tire001_Material_#1003_0" geometry={nodes['tire001_Material_#1003_0'].geometry} material={materials.Material_1003} />
                    <mesh name="tire001_Material_#1192_0" geometry={nodes['tire001_Material_#1192_0'].geometry} material={materials.Material_1192} />
                  </group>
                  <group name="brake001" position={[59.332, -11.246, 12.759]} scale={[1, 1, 0.516]}>
                    <group name="Object_84" position={[5.429, 7.302, 4.795]}>
                      <mesh name="brake001_Material_#1207_0" geometry={nodes['brake001_Material_#1207_0'].geometry} material={materials.Material_1207} />
                    </group>
                    <group name="brake_disc001" position={[-59.485, 11.611, -12.471]} scale={[1, 1, 0.851]}>
                      <group name="Object_87" position={[0, 0, 16.985]}>
                        <mesh name="brake_disc001_Material_#1208_0" geometry={nodes['brake_disc001_Material_#1208_0'].geometry} material={materials.Material_1208} />
                        <mesh name="brake_disc001_Acrylic_Opaque_Black_0" geometry={nodes.brake_disc001_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                      </group>
                    </group>
                  </group>
                  <group name="rim001" position={[0, 0, -0.575]}>
                    <group name="Object_91" position={[0, 0, -29.343]}>
                      <mesh name="rim001_Material_#1180_0" geometry={nodes['rim001_Material_#1180_0'].geometry} material={materials.Material_1180} />
                      <mesh name="rim001_Acrylic_Opaque_Black_0" geometry={nodes.rim001_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                    </group>
                  </group>
                </group>
                <group name="f_logo" position={[7.45, -829.634, 155.213]} rotation={[0.698, 0, 0]} scale={[1, 1.283, 1]}>
                  <mesh name="f_logo_Acrylic_Opaque_Black_0" geometry={nodes.f_logo_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                </group>
                <group name="seats" position={[3.311, 38.859, 268.501]}>
                  <mesh name="seats_Material_#1700_0" geometry={nodes['seats_Material_#1700_0'].geometry} material={materials.Material_1700} />
                  <mesh name="seats_Material_#1688_0" geometry={nodes['seats_Material_#1688_0'].geometry} material={materials.Material_1688} />
                  <mesh name="seats_Material_#1612_0" geometry={nodes['seats_Material_#1612_0'].geometry} material={materials.Material_1612} />
                  <mesh name="seats_black_0" geometry={nodes.seats_black_0.geometry} material={materials.black} />
                  <mesh name="seats_Acrylic_Opaque_Black_0" geometry={nodes.seats_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                  <mesh name="seats_silver_0" geometry={nodes.seats_silver_0.geometry} material={materials.silver} />
                </group>
                <group name="Steering_Wheel" position={[122.164, -204.508, 252.391]} rotation={[-1.396, 0, Math.PI]} scale={[0.327, 0.327, 0.398]}>
                  <mesh name="Steering_Wheel_Acrylic_Opaque_Black_0" geometry={nodes.Steering_Wheel_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                  <mesh name="Steering_Wheel_Material_#1396_0" geometry={nodes['Steering_Wheel_Material_#1396_0'].geometry} material={materials.Material_1396} />
                  <mesh name="Steering_Wheel_silver_0" geometry={nodes.Steering_Wheel_silver_0.geometry} material={materials.silver} />
                  <mesh name="Steering_Wheel_Material_#1449_0" geometry={nodes['Steering_Wheel_Material_#1449_0'].geometry} material={materials.Material_1449} />
                  <mesh name="Steering_Wheel_Material_#1435_0" geometry={nodes['Steering_Wheel_Material_#1435_0'].geometry} material={materials.Material_1435} />
                  <mesh name="Steering_Wheel_Material_#1448_0" geometry={nodes['Steering_Wheel_Material_#1448_0'].geometry} material={materials.Material_1448} />
                </group>
                <group name="tire003" position={[-306.85, -444.115, 119.02]} rotation={[Math.PI / 2, -1.571, 0]} scale={[1, 1, 2.278]}>
                  <group name="Object_122" position={[0, 0, -29.917]}>
                    <mesh name="tire003_Material_#1003_0" geometry={nodes['tire003_Material_#1003_0'].geometry} material={materials.Material_1003} />
                    <mesh name="tire003_Material_#1192_0" geometry={nodes['tire003_Material_#1192_0'].geometry} material={materials.Material_1192} />
                  </group>
                  <group name="brake003" position={[59.332, -11.246, 12.759]} scale={[1, 1, 0.516]}>
                    <group name="Object_126" position={[5.429, 7.302, 4.795]}>
                      <mesh name="brake003_Material_#1207_0" geometry={nodes['brake003_Material_#1207_0'].geometry} material={materials.Material_1207} />
                    </group>
                    <group name="brake_disc003" position={[-59.485, 11.611, -12.471]} scale={[1, 1, 0.851]}>
                      <group name="Object_129" position={[0, 0, 16.985]}>
                        <mesh name="brake_disc003_Material_#1208_0" geometry={nodes['brake_disc003_Material_#1208_0'].geometry} material={materials.Material_1208} />
                        <mesh name="brake_disc003_Acrylic_Opaque_Black_0" geometry={nodes.brake_disc003_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                      </group>
                    </group>
                  </group>
                  <group name="rim003" position={[0, 0, -0.575]}>
                    <group name="Object_133" position={[0, 0, -29.343]}>
                      <mesh name="rim003_Material_#1180_0" geometry={nodes['rim003_Material_#1180_0'].geometry} material={materials.Material_1180} />
                      <mesh name="rim003_Acrylic_Opaque_Black_0" geometry={nodes.rim003_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                    </group>
                  </group>
                </group>
                <group name="tire004" position={[-306.851, 598.625, 119.02]} rotation={[Math.PI / 2, -1.571, 0]} scale={[1, 1, 2.278]}>
                  <group name="Object_137" position={[0, 0, -29.917]}>
                    <mesh name="tire004_Material_#1003_0" geometry={nodes['tire004_Material_#1003_0'].geometry} material={materials.Material_1003} />
                    <mesh name="tire004_Material_#1192_0" geometry={nodes['tire004_Material_#1192_0'].geometry} material={materials.Material_1192} />
                  </group>
                  <group name="brake004" position={[59.332, -11.246, 12.759]} scale={[1, 1, 0.516]}>
                    <group name="Object_141" position={[5.429, 7.302, 4.795]}>
                      <mesh name="brake004_Material_#1207_0" geometry={nodes['brake004_Material_#1207_0'].geometry} material={materials.Material_1207} />
                    </group>
                    <group name="brake_disc004" position={[-59.485, 11.611, -12.471]} scale={[1, 1, 0.851]}>
                      <group name="Object_144" position={[0, 0, 16.985]}>
                        <mesh name="brake_disc004_Material_#1208_0" geometry={nodes['brake_disc004_Material_#1208_0'].geometry} material={materials.Material_1208} />
                        <mesh name="brake_disc004_Acrylic_Opaque_Black_0" geometry={nodes.brake_disc004_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                      </group>
                    </group>
                  </group>
                  <group name="rim004" position={[0, 0, -0.575]}>
                    <group name="Object_148" position={[0, 0, -29.343]}>
                      <mesh name="rim004_Material_#1180_0" geometry={nodes['rim004_Material_#1180_0'].geometry} material={materials.Material_1180} />
                      <mesh name="rim004_Acrylic_Opaque_Black_0" geometry={nodes.rim004_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                    </group>
                  </group>
                </group>
                <group name="w1_wiper" position={[21.58, -478.034, 281.843]}>
                  <group name="Object_152" position={[-18.269, 533.324, -8.306]}>
                    <mesh name="w1_wiper_Acrylic_Opaque_Black_0" geometry={nodes.w1_wiper_Acrylic_Opaque_Black_0.geometry} material={materials.Acrylic_Opaque_Black} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car2.glb')
