/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car3.glb 
Author: solid3DDD (https://sketchfab.com/solid3ddd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dacia-1300-widebody-lowpoly-b34abb81f31e45eb89f19eac82c72cbb
Title: Dacia 1300 Widebody LowPoly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.sportivaTexture} position={[0.847, 0.085, 0.914]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.glass} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.bottom} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.sportivaTexture} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.sportivaTexture} position={[-0.847, 0.085, 0.914]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.sportivaTexture} position={[0.847, 0.085, -1.399]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.sportivaTexture} position={[-0.847, 0.085, -1.399]} />
    </group>
  )
}

useGLTF.preload('/car3.glb')
