/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car4.glb 
Author: OUTPISTON (https://sketchfab.com/outpiston)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2005-porsche-911-gt2-b85a2e1464944eb280e5f683dd528776
Title: 2005 Porsche 911 GT2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car4.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.863, 0.321, 1.168]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.083, 1.083, 1.083]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Vehicle_Exterior_mm_misc} />
      </group>
      <group position={[-0.909, 0.321, -1.183]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.083, 1.083, 1.083]}>
        <mesh geometry={nodes.Object_9.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Vehicle_Exterior_mm_misc} />
      </group>
      <group position={[0.909, 0.321, -1.183]} rotation={[Math.PI / 2, 0, 0]} scale={1.083}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Vehicle_Exterior_mm_misc} />
      </group>
      <group position={[0.863, 0.321, 1.168]} rotation={[Math.PI / 2, 0, 0]} scale={1.083}>
        <mesh geometry={nodes.Object_61.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Vehicle_Exterior_mm_misc} />
      </group>
      <mesh geometry={nodes.Object_19.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.Vehicle_Exterior_mm_chassis} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.Vehicle_Exterior_mm_chassis} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/car4.glb')
