/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car5.glb 
Author: OUTPISTON (https://sketchfab.com/outpiston)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/1974-porsche-911-targa-29a2620f99ad439bb1cda23b74905b49
Title: 1974 Porsche 911 Targa
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car5.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.746, 0.294, -1.042]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.987, 0.987, 0.987]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Vehicle_Exterior_mm_misc} />
      </group>
      <group position={[-0.746, 0.294, 1.172]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.987, 0.987, 0.987]}>
        <mesh geometry={nodes.Object_9.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Vehicle_Exterior_mm_misc} />
      </group>
      <group position={[0.746, 0.294, 1.172]} rotation={[Math.PI / 2, 0, 0]} scale={0.987}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Vehicle_Exterior_mm_misc} />
      </group>
      <group position={[0.746, 0.294, -1.042]} rotation={[Math.PI / 2, 0, 0]} scale={0.987}>
        <mesh geometry={nodes.Object_19.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Vehicle_Exterior_mm_misc} />
      </group>
      <mesh geometry={nodes.Object_24.geometry} material={materials.Vehicle_Exterior_mm_chassis} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Vehicle_Exterior_mm_chassis} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/car5.glb')
