/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car6.glb 
Author: Artso12 (https://sketchfab.com/Artso12)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1962-pontiac-catalina-064a26e5580e481a8182b55f0a1ca167
Title: 1962 Pontiac Catalina
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car6.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.acmat0.geometry} material={materials.acmat0} />
          <mesh geometry={nodes.acmat1.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_1.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_2.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_3.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_4.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_5.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_6.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_7.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_8.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_9.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_10.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_11.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_12.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_13.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_14.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_15.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_16.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_17.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_18.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_19.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_20.geometry} material={materials.acmat1} />
          <mesh geometry={nodes.acmat1_21.geometry} material={materials.acmat1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car6.glb')
