/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 map.glb --types 
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/endurance-run-road-trip-adventure-5e1a4b70baa241959b72ae12fec1253d
Title: endurance run - road trip adventure
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['C20-51_C20-51_0']: THREE.Mesh
    ['C20-52_C20-52_0']: THREE.Mesh
    ['C20-53_C20-53_0']: THREE.Mesh
    ['C20-54_C20-54_0']: THREE.Mesh
    ['C20-55_C20-55_0']: THREE.Mesh
    ['C20-56_C20-56_0']: THREE.Mesh
    ['C20-57_C20-57_0']: THREE.Mesh
    ['C20-58_C20-58_0']: THREE.Mesh
    ['C20-59_C20-59_0']: THREE.Mesh
    ['C20-60_C20-60_0']: THREE.Mesh
    ['C20-61_C20-61_0']: THREE.Mesh
    ['C20-62_C20-62_0']: THREE.Mesh
    ['C20-63_C20-63_0']: THREE.Mesh
    ['C20-64_C20-64_0']: THREE.Mesh
    ['C20-65_C20-65_0']: THREE.Mesh
    ['C20-66_C20-66_0']: THREE.Mesh
    ['C20-67_C20-67_0']: THREE.Mesh
    ['C20-68_C20-68_0']: THREE.Mesh
    ['C20-69_C20-69_0']: THREE.Mesh
    ['C20-70_C20-70_0']: THREE.Mesh
    ['C20-71_C20-71_0']: THREE.Mesh
    ['C20-6_C20-6_0']: THREE.Mesh
    ['C20-7_C20-7_0']: THREE.Mesh
    ['C20-8_C20-8_0']: THREE.Mesh
    ['C20-9_C20-9_0']: THREE.Mesh
    ['C20-10_C20-10_0']: THREE.Mesh
    ['C20-11_C20-11_0']: THREE.Mesh
    ['C20-12_C20-12_0']: THREE.Mesh
    ['C20-13_C20-13_0']: THREE.Mesh
    ['C20-14_C20-14_0']: THREE.Mesh
    ['C20-15_C20-15_0']: THREE.Mesh
    ['C20-16_C20-16_0']: THREE.Mesh
    ['C20-17_C20-17_0']: THREE.Mesh
    ['C20-18_C20-18_0']: THREE.Mesh
    ['C20-19_C20-19_0']: THREE.Mesh
    ['C20-20_C20-20_0']: THREE.Mesh
    ['C20-21_C20-21_0']: THREE.Mesh
    ['C20-22_C20-22_0']: THREE.Mesh
    ['C20-23_C20-23_0']: THREE.Mesh
    ['C20-24_C20-24_0']: THREE.Mesh
    ['C20-25_C20-25_0']: THREE.Mesh
    ['C20-26_C20-26_0']: THREE.Mesh
    ['C20-27_C20-27_0']: THREE.Mesh
    ['C20-28_C20-28_0']: THREE.Mesh
    ['C20-29_C20-29_0']: THREE.Mesh
    ['C20-30_C20-30_0']: THREE.Mesh
    ['C20-31_C20-31_0']: THREE.Mesh
    ['C20-32_C20-32_0']: THREE.Mesh
    ['C20-33_C20-33_0']: THREE.Mesh
    ['C20-34_C20-34_0']: THREE.Mesh
    ['C20-35_C20-35_0']: THREE.Mesh
    ['C20-36_C20-36_0']: THREE.Mesh
    ['C20-37_C20-37_0']: THREE.Mesh
    ['C20-38_C20-38_0']: THREE.Mesh
    ['C20-39_C20-39_0']: THREE.Mesh
    ['C20-40_C20-40_0']: THREE.Mesh
    ['C20-41_C20-41_0']: THREE.Mesh
    ['C20-42_C20-42_0']: THREE.Mesh
    ['C20-43_C20-43_0']: THREE.Mesh
    ['C20-44_C20-44_0']: THREE.Mesh
    ['C20-45_C20-45_0']: THREE.Mesh
    ['C20-46_C20-46_0']: THREE.Mesh
    ['C20-47_C20-47_0']: THREE.Mesh
    ['C20-48_C20-48_0']: THREE.Mesh
    ['C20-49_C20-49_0']: THREE.Mesh
    ['C20-50_C20-50_0']: THREE.Mesh
    ['C20-0_C20-0_0']: THREE.Mesh
    ['C20-1_C20-1_0']: THREE.Mesh
    ['C20-2_C20-2_0']: THREE.Mesh
    ['C20-3_C20-3_0']: THREE.Mesh
    ['C20-4_C20-4_0']: THREE.Mesh
    ['C20-5_C20-5_0']: THREE.Mesh
  }
  materials: {
    ['C20-51']: THREE.MeshStandardMaterial
    ['C20-52']: THREE.MeshStandardMaterial
    ['C20-53']: THREE.MeshStandardMaterial
    ['C20-54']: THREE.MeshStandardMaterial
    ['C20-55']: THREE.MeshStandardMaterial
    ['C20-56']: THREE.MeshStandardMaterial
    ['C20-57']: THREE.MeshStandardMaterial
    ['C20-58']: THREE.MeshStandardMaterial
    ['C20-59']: THREE.MeshStandardMaterial
    ['C20-60']: THREE.MeshStandardMaterial
    ['C20-61']: THREE.MeshStandardMaterial
    ['C20-62']: THREE.MeshStandardMaterial
    ['C20-63']: THREE.MeshStandardMaterial
    ['C20-64']: THREE.MeshStandardMaterial
    ['C20-65']: THREE.MeshStandardMaterial
    ['C20-66']: THREE.MeshStandardMaterial
    ['C20-67']: THREE.MeshStandardMaterial
    ['C20-68']: THREE.MeshStandardMaterial
    ['C20-69']: THREE.MeshStandardMaterial
    ['C20-70']: THREE.MeshStandardMaterial
    ['C20-71']: THREE.MeshStandardMaterial
    ['C20-6']: THREE.MeshStandardMaterial
    ['C20-7']: THREE.MeshStandardMaterial
    ['C20-8']: THREE.MeshStandardMaterial
    ['C20-9']: THREE.MeshStandardMaterial
    ['C20-10']: THREE.MeshStandardMaterial
    ['C20-11']: THREE.MeshStandardMaterial
    ['C20-12']: THREE.MeshStandardMaterial
    ['C20-13']: THREE.MeshStandardMaterial
    ['C20-14']: THREE.MeshStandardMaterial
    ['C20-15']: THREE.MeshStandardMaterial
    ['C20-16']: THREE.MeshStandardMaterial
    ['C20-17']: THREE.MeshStandardMaterial
    ['C20-18']: THREE.MeshStandardMaterial
    ['C20-19']: THREE.MeshStandardMaterial
    ['C20-20']: THREE.MeshStandardMaterial
    ['C20-21']: THREE.MeshStandardMaterial
    ['C20-22']: THREE.MeshStandardMaterial
    ['C20-23']: THREE.MeshStandardMaterial
    ['C20-24']: THREE.MeshStandardMaterial
    ['C20-25']: THREE.MeshStandardMaterial
    ['C20-26']: THREE.MeshStandardMaterial
    ['C20-27']: THREE.MeshStandardMaterial
    ['C20-28']: THREE.MeshStandardMaterial
    ['C20-29']: THREE.MeshStandardMaterial
    ['C20-30']: THREE.MeshStandardMaterial
    ['C20-31']: THREE.MeshStandardMaterial
    ['C20-32']: THREE.MeshStandardMaterial
    ['C20-33']: THREE.MeshStandardMaterial
    ['C20-34']: THREE.MeshStandardMaterial
    ['C20-35']: THREE.MeshStandardMaterial
    ['C20-36']: THREE.MeshStandardMaterial
    ['C20-37']: THREE.MeshStandardMaterial
    ['C20-38']: THREE.MeshStandardMaterial
    ['C20-39']: THREE.MeshStandardMaterial
    ['C20-40']: THREE.MeshStandardMaterial
    ['C20-41']: THREE.MeshStandardMaterial
    ['C20-42']: THREE.MeshStandardMaterial
    ['C20-43']: THREE.MeshStandardMaterial
    ['C20-44']: THREE.MeshStandardMaterial
    ['C20-45']: THREE.MeshStandardMaterial
    ['C20-46']: THREE.MeshStandardMaterial
    ['C20-47']: THREE.MeshStandardMaterial
    ['C20-48']: THREE.MeshStandardMaterial
    ['C20-49']: THREE.MeshStandardMaterial
    ['C20-50']: THREE.MeshStandardMaterial
    ['C20-0']: THREE.MeshStandardMaterial
    ['C20-1']: THREE.MeshStandardMaterial
    ['C20-2']: THREE.MeshStandardMaterial
    ['C20-3']: THREE.MeshStandardMaterial
    ['C20-4']: THREE.MeshStandardMaterial
    ['C20-5']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/map.glb') as GLTFResult

  // Safety check: return null if nodes aren't loaded yet
  if (!nodes || !nodes['C20-51_C20-51_0']) {
    return null
  }

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['C20-51_C20-51_0'].geometry} material={materials['C20-51']} scale={100} />
        <mesh geometry={nodes['C20-52_C20-52_0'].geometry} material={materials['C20-52']} scale={100} />
        <mesh geometry={nodes['C20-53_C20-53_0'].geometry} material={materials['C20-53']} scale={100} />
        <mesh geometry={nodes['C20-54_C20-54_0'].geometry} material={materials['C20-54']} scale={100} />
        <mesh geometry={nodes['C20-55_C20-55_0'].geometry} material={materials['C20-55']} scale={100} />
        <mesh geometry={nodes['C20-56_C20-56_0'].geometry} material={materials['C20-56']} scale={100} />
        <mesh geometry={nodes['C20-57_C20-57_0'].geometry} material={materials['C20-57']} scale={100} />
        <mesh geometry={nodes['C20-58_C20-58_0'].geometry} material={materials['C20-58']} scale={100} />
        <mesh geometry={nodes['C20-59_C20-59_0'].geometry} material={materials['C20-59']} scale={100} />
        <mesh geometry={nodes['C20-60_C20-60_0'].geometry} material={materials['C20-60']} scale={100} />
        <mesh geometry={nodes['C20-61_C20-61_0'].geometry} material={materials['C20-61']} scale={100} />
        <mesh geometry={nodes['C20-62_C20-62_0'].geometry} material={materials['C20-62']} scale={100} />
        <mesh geometry={nodes['C20-63_C20-63_0'].geometry} material={materials['C20-63']} scale={100} />
        <mesh geometry={nodes['C20-64_C20-64_0'].geometry} material={materials['C20-64']} scale={100} />
        <mesh geometry={nodes['C20-65_C20-65_0'].geometry} material={materials['C20-65']} scale={100} />
        <mesh geometry={nodes['C20-66_C20-66_0'].geometry} material={materials['C20-66']} scale={100} />
        <mesh geometry={nodes['C20-67_C20-67_0'].geometry} material={materials['C20-67']} scale={100} />
        <mesh geometry={nodes['C20-68_C20-68_0'].geometry} material={materials['C20-68']} scale={100} />
        <mesh geometry={nodes['C20-69_C20-69_0'].geometry} material={materials['C20-69']} scale={100} />
        <mesh geometry={nodes['C20-70_C20-70_0'].geometry} material={materials['C20-70']} scale={100} />
        <mesh geometry={nodes['C20-71_C20-71_0'].geometry} material={materials['C20-71']} scale={100} />
        <mesh geometry={nodes['C20-6_C20-6_0'].geometry} material={materials['C20-6']} scale={100} />
        <mesh geometry={nodes['C20-7_C20-7_0'].geometry} material={materials['C20-7']} scale={100} />
        <mesh geometry={nodes['C20-8_C20-8_0'].geometry} material={materials['C20-8']} scale={100} />
        <mesh geometry={nodes['C20-9_C20-9_0'].geometry} material={materials['C20-9']} scale={100} />
        <mesh geometry={nodes['C20-10_C20-10_0'].geometry} material={materials['C20-10']} scale={100} />
        <mesh geometry={nodes['C20-11_C20-11_0'].geometry} material={materials['C20-11']} scale={100} />
        <mesh geometry={nodes['C20-12_C20-12_0'].geometry} material={materials['C20-12']} scale={100} />
        <mesh geometry={nodes['C20-13_C20-13_0'].geometry} material={materials['C20-13']} scale={100} />
        <mesh geometry={nodes['C20-14_C20-14_0'].geometry} material={materials['C20-14']} scale={100} />
        <mesh geometry={nodes['C20-15_C20-15_0'].geometry} material={materials['C20-15']} scale={100} />
        <mesh geometry={nodes['C20-16_C20-16_0'].geometry} material={materials['C20-16']} scale={100} />
        <mesh geometry={nodes['C20-17_C20-17_0'].geometry} material={materials['C20-17']} scale={100} />
        <mesh geometry={nodes['C20-18_C20-18_0'].geometry} material={materials['C20-18']} scale={100} />
        <mesh geometry={nodes['C20-19_C20-19_0'].geometry} material={materials['C20-19']} scale={100} />
        <mesh geometry={nodes['C20-20_C20-20_0'].geometry} material={materials['C20-20']} scale={100} />
        <mesh geometry={nodes['C20-21_C20-21_0'].geometry} material={materials['C20-21']} scale={100} />
        <mesh geometry={nodes['C20-22_C20-22_0'].geometry} material={materials['C20-22']} scale={100} />
        <mesh geometry={nodes['C20-23_C20-23_0'].geometry} material={materials['C20-23']} scale={100} />
        <mesh geometry={nodes['C20-24_C20-24_0'].geometry} material={materials['C20-24']} scale={100} />
        <mesh geometry={nodes['C20-25_C20-25_0'].geometry} material={materials['C20-25']} scale={100} />
        <mesh geometry={nodes['C20-26_C20-26_0'].geometry} material={materials['C20-26']} scale={100} />
        <mesh geometry={nodes['C20-27_C20-27_0'].geometry} material={materials['C20-27']} scale={100} />
        <mesh geometry={nodes['C20-28_C20-28_0'].geometry} material={materials['C20-28']} scale={100} />
        <mesh geometry={nodes['C20-29_C20-29_0'].geometry} material={materials['C20-29']} scale={100} />
        <mesh geometry={nodes['C20-30_C20-30_0'].geometry} material={materials['C20-30']} scale={100} />
        <mesh geometry={nodes['C20-31_C20-31_0'].geometry} material={materials['C20-31']} scale={100} />
        <mesh geometry={nodes['C20-32_C20-32_0'].geometry} material={materials['C20-32']} scale={100} />
        <mesh geometry={nodes['C20-33_C20-33_0'].geometry} material={materials['C20-33']} scale={100} />
        <mesh geometry={nodes['C20-34_C20-34_0'].geometry} material={materials['C20-34']} scale={100} />
        <mesh geometry={nodes['C20-35_C20-35_0'].geometry} material={materials['C20-35']} scale={100} />
        <mesh geometry={nodes['C20-36_C20-36_0'].geometry} material={materials['C20-36']} scale={100} />
        <mesh geometry={nodes['C20-37_C20-37_0'].geometry} material={materials['C20-37']} scale={100} />
        <mesh geometry={nodes['C20-38_C20-38_0'].geometry} material={materials['C20-38']} scale={100} />
        <mesh geometry={nodes['C20-39_C20-39_0'].geometry} material={materials['C20-39']} scale={100} />
        <mesh geometry={nodes['C20-40_C20-40_0'].geometry} material={materials['C20-40']} scale={100} />
        <mesh geometry={nodes['C20-41_C20-41_0'].geometry} material={materials['C20-41']} scale={100} />
        <mesh geometry={nodes['C20-42_C20-42_0'].geometry} material={materials['C20-42']} scale={100} />
        <mesh geometry={nodes['C20-43_C20-43_0'].geometry} material={materials['C20-43']} scale={100} />
        <mesh geometry={nodes['C20-44_C20-44_0'].geometry} material={materials['C20-44']} scale={100} />
        <mesh geometry={nodes['C20-45_C20-45_0'].geometry} material={materials['C20-45']} scale={100} />
        <mesh geometry={nodes['C20-46_C20-46_0'].geometry} material={materials['C20-46']} scale={100} />
        <mesh geometry={nodes['C20-47_C20-47_0'].geometry} material={materials['C20-47']} scale={100} />
        <mesh geometry={nodes['C20-48_C20-48_0'].geometry} material={materials['C20-48']} scale={100} />
        <mesh geometry={nodes['C20-49_C20-49_0'].geometry} material={materials['C20-49']} scale={100} />
        <mesh geometry={nodes['C20-50_C20-50_0'].geometry} material={materials['C20-50']} scale={100} />
        <mesh geometry={nodes['C20-0_C20-0_0'].geometry} material={materials['C20-0']} scale={100} />
        <mesh geometry={nodes['C20-1_C20-1_0'].geometry} material={materials['C20-1']} scale={100} />
        <mesh geometry={nodes['C20-2_C20-2_0'].geometry} material={materials['C20-2']} scale={100} />
        <mesh geometry={nodes['C20-3_C20-3_0'].geometry} material={materials['C20-3']} scale={100} />
        <mesh geometry={nodes['C20-4_C20-4_0'].geometry} material={materials['C20-4']} scale={100} />
        <mesh geometry={nodes['C20-5_C20-5_0'].geometry} material={materials['C20-5']} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/map.glb')
