/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Karolina Renkiewicz (https://sketchfab.com/KarolinaRenkiewicz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bitcoin-ff17dab54b044d789d05ae7c8dfb9808
Title: Bitcoin
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder002__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/bitcoin.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-3.489, 36.23, -11.294]}
      />
    </group>
  )
}

// Multiple coins for the track
export function Coins() {
  const { nodes, materials } = useGLTF('/bitcoin.glb') as unknown as GLTFResult

  // First set: 3 coins starting at X: 1080.6, Y: 0.2, Z: 611.2, spaced 5 units apart
  const firstSet = [
    [1080.6, 0.2, 611.2],
    [1080.6, 0.2, 616.2],
    [1080.6, 0.2, 621.2],
  ]

  // Second set: 5 coins starting at X: 1074.7, Y: 0.2, Z: 636.3, spaced 5 units apart
  const secondSet = [
    [1074.7, 0.2, 636.3],
    [1074.7, 0.2, 641.3],
    [1074.7, 0.2, 646.3],
    [1074.7, 0.2, 651.3],
    [1074.7, 0.2, 656.3],
  ]

  // Third set: 5 coins starting at X: 1066.1, Y: 0.2, Z: 664.6, spaced 10 units apart
  const thirdSet = [
    [1066.1, 0.2, 664.6],
    [1066.1, 0.2, 674.6],
    [1066.1, 0.2, 684.6],
    [1066.1, 0.2, 694.6],
    [1066.1, 0.2, 704.6],
  ]

  const allCoins = [...firstSet, ...secondSet, ...thirdSet]

  return (
    <group>
      {allCoins.map((position, index) => (
        <mesh
          key={index}
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002__0.geometry}
          material={materials['Scene_-_Root']}
          position={[position[0], position[1], position[2]]}
        />
      ))}
    </group>
  )
}

useGLTF.preload('/bitcoin.glb')
