/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: solid3DDD (https://sketchfab.com/solid3ddd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dacia-1300-widebody-lowpoly-b34abb81f31e45eb89f19eac82c72cbb
Title: Dacia 1300 Widebody LowPoly
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
  }
  materials: {
    sportivaTexture: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    bottom: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/car3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.sportivaTexture}
        position={[0.847, 0.085, 0.914]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.bottom}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.sportivaTexture}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.sportivaTexture}
        position={[-0.847, 0.085, 0.914]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.sportivaTexture}
        position={[0.847, 0.085, -1.399]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.sportivaTexture}
        position={[-0.847, 0.085, -1.399]}
      />
    </group>
  )
}

useGLTF.preload('/car3.glb')
