/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Outlaw Games™ (https://sketchfab.com/Outlaw_Games)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-aventador-e328d9f5dcfd48bdbe8c73324b52ece3
Title: Lamborghini Aventador
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_12: THREE.Mesh
    Object_15: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_24: THREE.Mesh
    Object_28: THREE.Mesh
    Object_31: THREE.Mesh
    Object_38: THREE.Mesh
    Object_41: THREE.Mesh
    Object_44: THREE.Mesh
    Object_48: THREE.Mesh
    Object_54: THREE.Mesh
    Object_60: THREE.Mesh
    Object_63: THREE.Mesh
    Object_66: THREE.Mesh
    Object_86: THREE.Mesh
    Object_99: THREE.Mesh
    Object_102: THREE.Mesh
    Object_105: THREE.Mesh
    Object_108: THREE.Mesh
    Object_111: THREE.Mesh
    Object_114: THREE.Mesh
    Object_127: THREE.Mesh
    Object_136: THREE.Mesh
    Object_140: THREE.Mesh
    Object_144: THREE.Mesh
    Object_147: THREE.Mesh
    Object_151: THREE.Mesh
    Object_154: THREE.Mesh
    Object_176: THREE.Mesh
    Object_184: THREE.Mesh
    Object_197: THREE.Mesh
    Object_204: THREE.Mesh
    Object_223: THREE.Mesh
    Object_225: THREE.Mesh
    Object_227: THREE.Mesh
    Object_229: THREE.Mesh
    Object_231: THREE.Mesh
    Object_232: THREE.Mesh
    Object_233: THREE.Mesh
    Object_235: THREE.Mesh
    Object_236: THREE.Mesh
    Object_237: THREE.Mesh
    Object_246: THREE.Mesh
    Object_247: THREE.Mesh
    Object_248: THREE.Mesh
    Object_250: THREE.Mesh
    Object_254: THREE.Mesh
    Object_256: THREE.Mesh
    Object_260: THREE.Mesh
    Object_262: THREE.Mesh
    Object_264: THREE.Mesh
    Object_267: THREE.Mesh
    Object_271: THREE.Mesh
    Object_274: THREE.Mesh
    Object_276: THREE.Mesh
    Object_277: THREE.Mesh
    Object_278: THREE.Mesh
    Object_279: THREE.Mesh
    Object_280: THREE.Mesh
    Object_281: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshPhysicalMaterial
    Body: THREE.MeshPhysicalMaterial
    Plastic: THREE.MeshPhysicalMaterial
    Red_Glass: THREE.MeshPhysicalMaterial
    Brakelights: THREE.MeshStandardMaterial
    Grille: THREE.MeshPhysicalMaterial
    Buttons: THREE.MeshStandardMaterial
    Display: THREE.MeshPhysicalMaterial
    ['Body_Colour_sv_interior.png']: THREE.MeshPhysicalMaterial
    Carbon_Fiber: THREE.MeshPhysicalMaterial
    Door_Badge: THREE.MeshStandardMaterial
    Badge: THREE.MeshPhysicalMaterial
    Engine: THREE.MeshPhysicalMaterial
    Inner_Engine: THREE.MeshStandardMaterial
    Metallic_Engine_Logo: THREE.MeshStandardMaterial
    Suspension_Spring: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    ['Frame.001']: THREE.MeshPhysicalMaterial
    Interior: THREE.MeshPhysicalMaterial
    Leather: THREE.MeshPhysicalMaterial
    Plastic_Dash: THREE.MeshStandardMaterial
    Seat_Belt: THREE.MeshPhysicalMaterial
    Vents: THREE.MeshStandardMaterial
    Interior_Body_Colour: THREE.MeshPhysicalMaterial
    Mirror: THREE.MeshPhysicalMaterial
    Glass: THREE.MeshPhysicalMaterial
    Left_Signal: THREE.MeshPhysicalMaterial
    Right_Signal: THREE.MeshPhysicalMaterial
    Steering_Wheel: THREE.MeshPhysicalMaterial
    Steering_Wheel_Logo: THREE.MeshStandardMaterial
    Moket: THREE.MeshStandardMaterial
    Seat_Badge: THREE.MeshPhysicalMaterial
    Seat: THREE.MeshPhysicalMaterial
    ['Mat_cheetah.046']: THREE.MeshStandardMaterial
    Grille_5: THREE.MeshPhysicalMaterial
    ['License_Plate.001']: THREE.MeshPhysicalMaterial
    License_Plate_Background: THREE.MeshStandardMaterial
    Radiator: THREE.MeshPhysicalMaterial
    Right_Indicator: THREE.MeshStandardMaterial
    Ridge: THREE.MeshStandardMaterial
    Left_Indicator: THREE.MeshStandardMaterial
    ['Refractive_Lights_Glass_IOR_of_1.45']: THREE.MeshPhysicalMaterial
    Headlights: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshPhysicalMaterial
    Taillights_Glass: THREE.MeshStandardMaterial
    Lights_not_emissive: THREE.MeshStandardMaterial
    Rear_Marking_Lights: THREE.MeshStandardMaterial
    ['Black.001']: THREE.MeshPhysicalMaterial
    Black_Metal: THREE.MeshPhysicalMaterial
    ['Carbon_Fiber.001']: THREE.MeshPhysicalMaterial
    ['Grille-1']: THREE.MeshPhysicalMaterial
    ['Grille-2']: THREE.MeshPhysicalMaterial
    Chrome: THREE.MeshStandardMaterial
    Carpet: THREE.MeshStandardMaterial
    ['material.001']: THREE.MeshPhysicalMaterial
    ['Dark_Glass.001']: THREE.MeshPhysicalMaterial
    material_63: THREE.MeshPhysicalMaterial
    Brake_Caliper_Color: THREE.MeshPhysicalMaterial
    Brake_Caliper_Logo: THREE.MeshStandardMaterial
    Emblems: THREE.MeshPhysicalMaterial
    ['Brake_Disc.001']: THREE.MeshPhysicalMaterial
    Tire: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/car6.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Black}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.Body}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Plastic}
        position={[2.282, 0.808, -0.003]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Red_Glass}
        position={[2.282, 0.808, -0.003]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.Brakelights}
        position={[2.282, 0.808, -0.003]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.Grille}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.Buttons}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.Display}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials['Body_Colour_sv_interior.png']}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials.Carbon_Fiber}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.Door_Badge}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.Badge}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.Engine}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.Inner_Engine}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_63.geometry}
        material={materials.Metallic_Engine_Logo}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials.Suspension_Spring}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials.Metal}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_99.geometry}
        material={materials['Frame.001']}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials.Interior}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_105.geometry}
        material={materials.Leather}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials.Plastic_Dash}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_111.geometry}
        material={materials.Seat_Belt}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials.Vents}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_127.geometry}
        material={materials.Interior_Body_Colour}
        position={[-0.651, 0.606, 0.875]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        material={materials.Mirror}
        position={[-0.651, 0.606, 0.875]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials.Glass}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials.Left_Signal}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_147.geometry}
        material={materials.Right_Signal}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_151.geometry}
        material={materials.Steering_Wheel}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials.Steering_Wheel_Logo}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_176.geometry}
        material={materials.Moket}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_184.geometry}
        material={materials.Seat_Badge}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_197.geometry}
        material={materials.Seat}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_204.geometry}
        material={materials['Mat_cheetah.046']}
        position={[0.033, 0.016, 0.022]}
        rotation={[2.99, 1.557, -2.984]}
        scale={0.875}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_223.geometry}
        material={materials.Grille_5}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_225.geometry}
        material={materials['License_Plate.001']}
        position={[2.368, 0.368, -0.002]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_227.geometry}
        material={materials.License_Plate_Background}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_229.geometry}
        material={materials.Radiator}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_231.geometry}
        material={materials.Right_Indicator}
        position={[-1.724, 0.538, 0.049]}
        rotation={[-1.565, -0.016, 1.584]}
        scale={0.877}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_232.geometry}
        material={materials.Ridge}
        position={[-1.724, 0.538, 0.049]}
        rotation={[-1.565, -0.016, 1.584]}
        scale={0.877}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_233.geometry}
        material={materials.Left_Indicator}
        position={[-1.724, 0.538, 0.049]}
        rotation={[-1.565, -0.016, 1.584]}
        scale={0.877}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_235.geometry}
        material={materials['Refractive_Lights_Glass_IOR_of_1.45']}
        position={[-1.724, 0.538, 0.049]}
        rotation={[-1.565, -0.016, 1.584]}
        scale={0.877}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_236.geometry}
        material={materials.Headlights}
        position={[-1.724, 0.538, 0.049]}
        rotation={[-1.565, -0.016, 1.584]}
        scale={0.877}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_237.geometry}
        material={materials['Glass.001']}
        position={[-1.724, 0.538, 0.049]}
        rotation={[-1.565, -0.016, 1.584]}
        scale={0.877}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_246.geometry}
        material={materials.Taillights_Glass}
        position={[2.221, 0.718, -0.005]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_247.geometry}
        material={materials.Lights_not_emissive}
        position={[2.221, 0.718, -0.005]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_248.geometry}
        material={materials.Rear_Marking_Lights}
        position={[2.221, 0.718, -0.005]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_250.geometry}
        material={materials['Black.001']}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_254.geometry}
        material={materials.Black_Metal}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_256.geometry}
        material={materials['Carbon_Fiber.001']}
        position={[2.239, 0.352, -0.005]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_260.geometry}
        material={materials['Grille-1']}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_262.geometry}
        material={materials['Grille-2']}
        position={[2.319, 0.57, -0.002]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_264.geometry}
        material={materials.Chrome}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_267.geometry}
        material={materials.Carpet}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_271.geometry}
        material={materials['material.001']}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_274.geometry}
        material={materials['Dark_Glass.001']}
        position={[0.033, -0.003, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_276.geometry}
        material={materials.material_63}
        position={[0.033, 0.007, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_277.geometry}
        material={materials.Brake_Caliper_Color}
        position={[0.033, 0.007, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_278.geometry}
        material={materials.Brake_Caliper_Logo}
        position={[0.033, 0.007, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_279.geometry}
        material={materials.Emblems}
        position={[0.033, 0.007, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_280.geometry}
        material={materials['Brake_Disc.001']}
        position={[0.033, 0.007, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_281.geometry}
        material={materials.Tire}
        position={[0.033, 0.007, 0.022]}
        rotation={[-1.565, 0.002, 1.584]}
        scale={0.871}
      />
    </group>
  )
}

useGLTF.preload('/car6.glb')
