/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pasha (https://sketchfab.com/Pasha.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/city-map-8a3ad92729da40f7b26a5f6e956a5382
Title: city map
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Material2: THREE.Mesh
    Material3: THREE.Mesh
    Material3_1: THREE.Mesh
    Material2_1: THREE.Mesh
    Material4: THREE.Mesh
    Material3_2: THREE.Mesh
    Material2_2: THREE.Mesh
    Material3_3: THREE.Mesh
    Material2_3: THREE.Mesh
    Material3_4: THREE.Mesh
    Material3_5: THREE.Mesh
    Material3_6: THREE.Mesh
    Material3_7: THREE.Mesh
    Material3_8: THREE.Mesh
    Material3_9: THREE.Mesh
    Material3_10: THREE.Mesh
    Material3_11: THREE.Mesh
    Material2_4: THREE.Mesh
    Material3_12: THREE.Mesh
    Material3_13: THREE.Mesh
    Material3_14: THREE.Mesh
    Material3_15: THREE.Mesh
    Material3_16: THREE.Mesh
    Material3_17: THREE.Mesh
    Material2_5: THREE.Mesh
    Material3_18: THREE.Mesh
    Material3_19: THREE.Mesh
    Material3_20: THREE.Mesh
    Material3_21: THREE.Mesh
    Material3_22: THREE.Mesh
    Material3_23: THREE.Mesh
    Material3_24: THREE.Mesh
    Material3_25: THREE.Mesh
    Material3_26: THREE.Mesh
    Material3_27: THREE.Mesh
    Material3_28: THREE.Mesh
    Material3_29: THREE.Mesh
    Material3_30: THREE.Mesh
    Material3_31: THREE.Mesh
    Material2_6: THREE.Mesh
    Material2_7: THREE.Mesh
    Material3_32: THREE.Mesh
    Material3_33: THREE.Mesh
    Material3_34: THREE.Mesh
    Material3_35: THREE.Mesh
    Material3_36: THREE.Mesh
    Material3_37: THREE.Mesh
    Material2_8: THREE.Mesh
    Material3_38: THREE.Mesh
    Material3_39: THREE.Mesh
    Material3_40: THREE.Mesh
    Material2_9: THREE.Mesh
    Material3_41: THREE.Mesh
    Material3_42: THREE.Mesh
    Material3_43: THREE.Mesh
    Material3_44: THREE.Mesh
    Material4_1: THREE.Mesh
    Material3_45: THREE.Mesh
    Material3_46: THREE.Mesh
    Material2_10: THREE.Mesh
    Material3_47: THREE.Mesh
    Material3_48: THREE.Mesh
    Material3_49: THREE.Mesh
    Material3_50: THREE.Mesh
    Material3_51: THREE.Mesh
    Material2_11: THREE.Mesh
    Material3_52: THREE.Mesh
    Material2_12: THREE.Mesh
    Material2_13: THREE.Mesh
    Material2_14: THREE.Mesh
    Material2_15: THREE.Mesh
    Material2_16: THREE.Mesh
    Material2_17: THREE.Mesh
    Material2_18: THREE.Mesh
    Material2_19: THREE.Mesh
    Material3_53: THREE.Mesh
    Material2_20: THREE.Mesh
    Material2_21: THREE.Mesh
    Material2_22: THREE.Mesh
    Material3_54: THREE.Mesh
    Material2_23: THREE.Mesh
    Material3_55: THREE.Mesh
    Material3_56: THREE.Mesh
    Material3_57: THREE.Mesh
    Material3_58: THREE.Mesh
    Material2_24: THREE.Mesh
  }
  materials: {
    Fencing_Lattice_Natural: THREE.MeshStandardMaterial
    Stone_Tile_Squares: THREE.MeshStandardMaterial
    Groundcover_Cedar2: THREE.MeshStandardMaterial
    Vegetation_Grass1: THREE.MeshPhysicalMaterial
    Asphalt_Old: THREE.MeshStandardMaterial
    Groundcover_Sand_12: THREE.MeshPhysicalMaterial
    material: THREE.MeshStandardMaterial
    Reed___Court_Parking_Garage: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    ['Untitled-61']: THREE.MeshStandardMaterial
    ablakok_13: THREE.MeshStandardMaterial
    Hochhaus_065: THREE.MeshStandardMaterial
    hochhauss: THREE.MeshStandardMaterial
    Metal_Rusted: THREE.MeshStandardMaterial
    dull_office_building_050941: THREE.MeshStandardMaterial
    azveg: THREE.MeshStandardMaterial
    glass: THREE.MeshPhysicalMaterial
    Material4: THREE.MeshStandardMaterial
    hausfront2: THREE.MeshStandardMaterial
    ['Stone-squares_1']: THREE.MeshStandardMaterial
    ['Galileo_Stone-squares1']: THREE.MeshStandardMaterial
    Galileo_Windows1: THREE.MeshStandardMaterial
    Roofing_Metal_Standing_Seam_Red: THREE.MeshStandardMaterial
    ['Untitled-4']: THREE.MeshStandardMaterial
    ['Stone-squares']: THREE.MeshStandardMaterial
    ['Untitled-55651_14']: THREE.MeshStandardMaterial
    ['Untitled-991']: THREE.MeshStandardMaterial
    ['Pavers-brick']: THREE.MeshStandardMaterial
    ['Untitled-2']: THREE.MeshStandardMaterial
    Seashell: THREE.MeshStandardMaterial
    Vinyl_Blue: THREE.MeshStandardMaterial
    Stucco: THREE.MeshStandardMaterial
    Gray: THREE.MeshStandardMaterial
    ['Untitled-7']: THREE.MeshStandardMaterial
    Brick_Dark_4: THREE.MeshStandardMaterial
    ['Untitled-3']: THREE.MeshStandardMaterial
    ['Untitled-666']: THREE.MeshStandardMaterial
    material_2_9: THREE.MeshStandardMaterial
    material_3: THREE.MeshStandardMaterial
    ['Concrete-rough_2']: THREE.MeshStandardMaterial
    Color_B13: THREE.MeshStandardMaterial
    Seashell_1: THREE.MeshStandardMaterial
    material_5: THREE.MeshStandardMaterial
    ['Untitled-5']: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
    ['Untitled-1']: THREE.MeshStandardMaterial
    Roofing_Slate_Red_1: THREE.MeshPhysicalMaterial
    ['Galileo_Stone-squares']: THREE.MeshPhysicalMaterial
    material_9: THREE.MeshStandardMaterial
    material_6_15: THREE.MeshStandardMaterial
    Beige_1: THREE.MeshStandardMaterial
    Color_1: THREE.MeshStandardMaterial
    Tile_Ceramic_12inch: THREE.MeshStandardMaterial
    Brick_Flemish_Bond_3: THREE.MeshStandardMaterial
    Water_Deep: THREE.MeshPhysicalMaterial
    Metal_Corrogated_Shiny: THREE.MeshStandardMaterial
    Blinds_Cloth_Horizontal: THREE.MeshStandardMaterial
    Asphalt_Old1: THREE.MeshStandardMaterial
    Seashell_5: THREE.MeshStandardMaterial
    Fountain_Water: THREE.MeshStandardMaterial
    Vegetation_Grass_Pattern: THREE.MeshStandardMaterial
    BuildingsHighRise0077_thumb: THREE.MeshStandardMaterial
    BuildingsHighRise0087_1_thumb: THREE.MeshStandardMaterial
    BuildingsHighRise0112_thumb: THREE.MeshStandardMaterial
    BuildingsHighRise0083_thumb: THREE.MeshStandardMaterial
    Groundcover_Sand: THREE.MeshStandardMaterial
    Redwood: THREE.MeshStandardMaterial
    Gray_Glass_1: THREE.MeshStandardMaterial
    Roofing_Slate_Red: THREE.MeshStandardMaterial
    material_2: THREE.MeshStandardMaterial
    leaves: THREE.MeshStandardMaterial
    Vegetation_Bark_Ponderosa: THREE.MeshStandardMaterial
    material_6: THREE.MeshStandardMaterial
    Color_C03: THREE.MeshStandardMaterial
    material_7: THREE.MeshStandardMaterial
    Billboard1: THREE.MeshStandardMaterial
    fountain: THREE.MeshStandardMaterial
    do_not_enter: THREE.MeshStandardMaterial
    Translucent_Glass_Gold: THREE.MeshStandardMaterial
    Sketchy_Lines_Wavy_Vertical: THREE.MeshStandardMaterial
    Color_000_5: THREE.MeshStandardMaterial
    Wavy_Crosshatch: THREE.MeshStandardMaterial
    Merged_materials: THREE.MeshStandardMaterial
    edge_color139141146255: THREE.LineBasicMaterial
    Charcoal_1: THREE.MeshStandardMaterial
    Green_1: THREE.MeshStandardMaterial
    ['0009_Linen']: THREE.MeshStandardMaterial
    Merged_materials: THREE.LineBasicMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/map.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2.geometry}
        material={materials.Fencing_Lattice_Natural}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3.geometry}
        material={materials.Stone_Tile_Squares}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_1.geometry}
        material={materials.Groundcover_Cedar2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_1.geometry}
        material={materials.Vegetation_Grass1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material4.geometry}
        material={materials.Asphalt_Old}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_2.geometry}
        material={materials.Groundcover_Sand_12}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_2.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_3.geometry}
        material={materials.Reed___Court_Parking_Garage}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_3.geometry}
        material={materials.Black}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_4.geometry}
        material={materials['Untitled-61']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_5.geometry}
        material={materials.ablakok_13}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_6.geometry}
        material={materials.Hochhaus_065}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_7.geometry}
        material={materials.hochhauss}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_8.geometry}
        material={materials.Metal_Rusted}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_9.geometry}
        material={materials.dull_office_building_050941}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_10.geometry}
        material={materials.azveg}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_11.geometry}
        material={materials.glass}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_4.geometry}
        material={materials.Material4}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_12.geometry}
        material={materials.hausfront2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_13.geometry}
        material={materials['Stone-squares_1']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_14.geometry}
        material={materials['Galileo_Stone-squares1']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_15.geometry}
        material={materials.Galileo_Windows1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_16.geometry}
        material={materials.Roofing_Metal_Standing_Seam_Red}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_17.geometry}
        material={materials['Untitled-4']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_5.geometry}
        material={materials['Stone-squares']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_18.geometry}
        material={materials['Untitled-55651_14']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_19.geometry}
        material={materials['Untitled-991']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_20.geometry}
        material={materials['Pavers-brick']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_21.geometry}
        material={materials['Untitled-2']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_22.geometry}
        material={materials.Seashell}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_23.geometry}
        material={materials.Vinyl_Blue}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_24.geometry}
        material={materials.Stucco}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_25.geometry}
        material={materials.Gray}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_26.geometry}
        material={materials['Untitled-7']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_27.geometry}
        material={materials.Brick_Dark_4}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_28.geometry}
        material={materials['Untitled-3']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_29.geometry}
        material={materials['Untitled-666']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_30.geometry}
        material={materials.material_2_9}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_31.geometry}
        material={materials.material_3}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_6.geometry}
        material={materials['Concrete-rough_2']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_7.geometry}
        material={materials.Color_B13}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_32.geometry}
        material={materials.Seashell_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_33.geometry}
        material={materials.material_5}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_34.geometry}
        material={materials['Untitled-5']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_35.geometry}
        material={materials.material_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_36.geometry}
        material={materials['Untitled-1']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_37.geometry}
        material={materials.Roofing_Slate_Red_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_8.geometry}
        material={materials['Galileo_Stone-squares']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_38.geometry}
        material={materials.material_9}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_39.geometry}
        material={materials.material_6_15}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_40.geometry}
        material={materials.Beige_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_9.geometry}
        material={materials.Color_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_41.geometry}
        material={materials.Tile_Ceramic_12inch}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_42.geometry}
        material={materials.Brick_Flemish_Bond_3}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_43.geometry}
        material={materials.Water_Deep}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_44.geometry}
        material={materials.Metal_Corrogated_Shiny}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material4_1.geometry}
        material={materials.Blinds_Cloth_Horizontal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_45.geometry}
        material={materials.Asphalt_Old1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_46.geometry}
        material={materials.Seashell_5}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_10.geometry}
        material={materials.Fountain_Water}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_47.geometry}
        material={materials.Vegetation_Grass_Pattern}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_48.geometry}
        material={materials.BuildingsHighRise0077_thumb}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_49.geometry}
        material={materials.BuildingsHighRise0087_1_thumb}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_50.geometry}
        material={materials.BuildingsHighRise0112_thumb}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_51.geometry}
        material={materials.BuildingsHighRise0083_thumb}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_11.geometry}
        material={materials.Groundcover_Sand}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_52.geometry}
        material={materials.Redwood}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_12.geometry}
        material={materials.Gray_Glass_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_13.geometry}
        material={materials.Roofing_Slate_Red}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_14.geometry}
        material={materials.material_2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_15.geometry}
        material={materials.leaves}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_16.geometry}
        material={materials.Vegetation_Bark_Ponderosa}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_17.geometry}
        material={materials.material_6}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_18.geometry}
        material={materials.Color_C03}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_19.geometry}
        material={materials.material_7}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_53.geometry}
        material={materials.Billboard1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_20.geometry}
        material={materials.fountain}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_21.geometry}
        material={materials.do_not_enter}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_22.geometry}
        material={materials.Translucent_Glass_Gold}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_54.geometry}
        material={materials.Sketchy_Lines_Wavy_Vertical}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_23.geometry}
        material={materials.Color_000_5}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_55.geometry}
        material={materials.Wavy_Crosshatch}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_56.geometry}
        material={materials.Merged_materials}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <lineSegments
        geometry={nodes.Material5.geometry}
        material={materials.edge_color139141146255}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_57.geometry}
        material={materials.Charcoal_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3_58.geometry}
        material={materials.Green_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_24.geometry}
        material={materials['0009_Linen']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <lineSegments
        geometry={nodes.Material2_25.geometry}
        material={materials.Merged_materials}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/map.glb')
